/**
 * mmemory — Built-in inline lifecycle extension.
 *
 * Inspired by Hindsight (https://github.com/vectorize-io/hindsight) by Vectorize — Apache 2.0.
 * See research/omp/dist-templates/extensions/mmemory.README.md for attribution.
 *
 * Registered as an inline ExtensionFactory in sdk.ts alongside createAutoresearchExtension.
 * No sidecar file needed — compiled into the binary.
 *
 * Responsibilities:
 *   - Auto-recall on first agent turn (inject <memories> into system prompt)
 *   - Auto-retain on agent_end (every N turns)
 *   - .memory prefix → inject <memory_mode> directive
 *   - session.compacting → inject recall snippet into compaction context
 *   - Server lifecycle (shared via getOrCreateServerClient in tools/mmemory/index.ts)
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { settings } from "./config/settings";
import type { AgentMessage } from "@oh-my-pi/pi-agent-core";
import type { ExtensionAPI, ExtensionContext } from "./extensibility/extensions";
import {
	disposeServerClient,
	executeMemoryBuild,
	executeMemoryRecall,
	formatRecallForSystemPrompt,
	loadMmemoryConfig,
	resolvePaths,
} from "./tools/mmemory/index";

// ── Session state ─────────────────────────────────────────────────────────────

interface MmemorySessionState {
	readonly config: import("./tools/mmemory/index").MmemoryConfig;
	readonly memoryDir: string;
	readonly sessionId: string;
	lastRecallSnippet: string | undefined;
	hasRecalledForFirstTurn: boolean;
	lastRetainedTurn: number;
	turnCount: number;
}

function createSessionState(ctx: ExtensionContext): MmemorySessionState | null {
	const config = loadMmemoryConfig(settings, ctx.cwd);
	if (!config) return null;
	const { memoryDir } = resolvePaths(config);

	// Scaffold storage directory + kb_config.yaml on first use
	const isNew = !fs.existsSync(memoryDir);
	fs.mkdirSync(memoryDir, { recursive: true });
	if (isNew) {
		console.log(`[mmemory] Created memory store: ${memoryDir}`);
		const kbConfigPath = path.join(memoryDir, "..", "kb_config.yaml");
		if (!fs.existsSync(kbConfigPath)) {
			fs.writeFileSync(
				kbConfigPath,
				`# Auto-generated by mmemory extension. DO NOT edit the type/handler fields.\n` +
				`${config.projectName}:\n` +
				`  type: external\n` +
				`  handler: mmemory\n` +
				`  description: "Managed by mmemory — use /mmemory commands, not kb_update"\n`,
				"utf-8",
			);
			console.log(`[mmemory] Created ${kbConfigPath}`);
		}
	}

	return {
		config,
		memoryDir,
		sessionId: Date.now().toString(36) + Math.random().toString(36).slice(2, 7),
		lastRecallSnippet: undefined,
		hasRecalledForFirstTurn: false,
		lastRetainedTurn: 0,
		turnCount: 0,
	};
}

function buildTranscript(messages: { role: string; content: unknown }[], contextTurns: number): string {
	const relevant = contextTurns > 0 ? messages.slice(-contextTurns * 2) : messages;
	const parts: string[] = [];
	for (const m of relevant) {
		const text = Array.isArray(m.content)
			? (m.content as { type: string; text?: string }[])
				.filter(c => c.type === "text")
				.map(c => c.text ?? "")
				.join(" ")
			: String(m.content ?? "");
		if (!text.trim()) continue;
		if (m.role === "user") parts.push(`**User:** ${text.trim()}`);
		else if (m.role === "assistant") parts.push(`**Assistant:** ${text.slice(0, 1000).trim()}`);
	}
	return parts.join("\n\n");
}

async function retainSession(state: MmemorySessionState, messages: { role: string; content: unknown }[]): Promise<void> {
	const transcript = buildTranscript(messages, state.config.retainContextTurns);
	if (!transcript) return;

	const extracted =
		state.config.extractionMode === "verbatim"
			? transcript
			: `<!-- extracted ${new Date().toISOString()} -->\n${transcript}`;

	const today = new Date().toISOString().slice(0, 10);
	const filePath = path.join(state.memoryDir, `${today}-${state.sessionId}.md`);
	fs.writeFileSync(
		filePath,
		`# Memory — ${today}\n\n**Mission:** ${state.config.retainMission}\n\n${extracted}`,
		"utf-8",
	);

	// Background re-index via shared server client
	void executeMemoryBuild(state.config).catch(() => {});
}

// ── Extension factory ─────────────────────────────────────────────────────────

const sessionMap = new WeakMap<ExtensionContext, MmemorySessionState>();

export function createMmemoryExtension(api: ExtensionAPI): void {
	api.setLabel("mmemory");

	api.on("session_start", (_event, ctx) => {
		const state = createSessionState(ctx);
		if (!state) return;
		sessionMap.set(ctx, state);
	});

	api.on("before_agent_start", async (event, ctx) => {
		const state = sessionMap.get(ctx);
		if (!state) return undefined;

		state.turnCount++;
		const prompt = (event as { prompt?: string }).prompt ?? "";
		const systemPrompt = (event as { systemPrompt?: string }).systemPrompt ?? "";

		// .memory prefix — inject memory_mode directive
		if (prompt.startsWith(".memory ")) {
			const query = prompt.slice(".memory ".length).trim();
			return {
				systemPrompt:
					systemPrompt.trimEnd() +
					"\n\n<memory_mode>\n" +
					"Direct memory request. Use mmemory_recall, mmemory_retain, or mmemory_reflect " +
					"immediately based on the user's intent.\n" +
					`Query: ${query}\n` +
					"</memory_mode>",
			};
		}

		// First turn: fire-and-forget recall with deadline
		if (!state.hasRecalledForFirstTurn) {
			state.hasRecalledForFirstTurn = true;
			const result = await executeMemoryRecall(prompt.slice(0, 400), undefined, state.config).catch(
				() => null,
			);
			const snippet = result ? formatRecallForSystemPrompt(result) : undefined;
			if (snippet) {
				state.lastRecallSnippet = snippet;
				return { systemPrompt: systemPrompt.trimEnd() + "\n\n" + snippet };
			}
		}

		// Subsequent turns: inject cached snippet
		if (state.lastRecallSnippet) {
			return { systemPrompt: systemPrompt.trimEnd() + "\n\n" + state.lastRecallSnippet };
		}

		return undefined;
	});

	api.on("agent_end", async (event, ctx) => {
		const state = sessionMap.get(ctx);
		if (!state?.config.autoRetain) return;
		if (state.turnCount - state.lastRetainedTurn < state.config.retainEveryNTurns) return;

		const messages = (event as { messages?: { role: string; content: unknown }[] }).messages ?? [];
		state.lastRetainedTurn = state.turnCount;
		void retainSession(state, messages).catch(() => {});
	});

	api.on("session.compacting", async (event, ctx) => {
		const state = sessionMap.get(ctx);
		if (!state) return undefined;

		const messages: AgentMessage[] = event.messages ?? [];
		const firstUser = messages.find(m => m.role === "user");
		const query = firstUser
			? (Array.isArray(firstUser.content)
					? (firstUser.content as { type: string; text?: string }[])
						.filter(c => c.type === "text")
						.map(c => c.text ?? "")
						.join(" ")
					: String(firstUser.content ?? "")
			  ).slice(0, 400)
			: "project context";

		const result = await executeMemoryRecall(query, undefined, state.config).catch(() => null);
		const snippet = result ? formatRecallForSystemPrompt(result) : undefined;
		return snippet ? { context: [snippet] } : undefined;
	});

	api.on("session_shutdown", (_event, ctx) => {
		const state = sessionMap.get(ctx);
		if (state) {
			disposeServerClient(state.config);
			sessionMap.delete(ctx);
		}
	});
}
