/**
 * mmemory — Built-in inline lifecycle extension.
 *
 * Inspired by Hindsight (https://github.com/vectorize-io/hindsight) by Vectorize — Apache 2.0.
 *
 * Registered as an inline ExtensionFactory in sdk.ts alongside createAutoresearchExtension.
 * No sidecar file needed — compiled into the binary.
 *
 * Responsibilities:
 *   - Auto-recall on first agent turn (inject <memories> into system prompt)
 *   - Auto-retain on agent_end (every N turns) — suppressed for subagents (taskDepth > 0)
 *   - .memory prefix → inject <memory_mode> directive
 *   - session.compacting → inject recall snippet into compaction context
 *   - Server lifecycle (shared via getOrCreateServerClient in tools/mmemory/index.ts)
 */
import { logger } from "@oh-my-pi/pi-utils";
import * as fs from "node:fs";
import * as path from "node:path";
import { settings } from "./config/settings";
import type { AgentMessage } from "@oh-my-pi/pi-agent-core";
import type { ExtensionAPI, ExtensionContext } from "./extensibility/extensions";
import type { ReadonlySessionManager } from "./session/session-manager";
import { completeSimple, validateToolCall } from "@oh-my-pi/pi-ai";
import type { ToolCall } from "@oh-my-pi/pi-ai";
import { Type } from "@sinclair/typebox";
import { resolveModelRoleValue } from "./config/model-resolver";
import {
	STRIP_TAGS_REGEX,
	composeRecallQuery,
	disposeServerClient,
	executeMemoryBuild,
	executeMemoryExtract,
	executeMemoryRecall,
	formatRecallForSystemPrompt,
	loadMentalModels,
	loadMmemoryConfig,
	resolvePaths,
	sessionFilename,
	truncateRecallQuery,
} from "./tools/mmemory/index";

// ── Session state ─────────────────────────────────────────────────────────────

interface MmemorySessionState {
	readonly config: import("./tools/mmemory/index").MmemoryConfig;
	readonly queueDir: string;
	readonly sessionId: string;
	readonly sessionStartTime: Date;
	lastRecallSnippet: string | undefined;
	mentalModelsSnippet: string | undefined;
	hasRecalledForFirstTurn: boolean;
	lastRetainedTurn: number;
	turnCount: number;
}

function createSessionState(ctx: ExtensionContext): MmemorySessionState | null {
	// Subagent guard: subagents must not auto-retain — their exploration transcripts
	// would pollute the memory store with internal monologue.
	if (ctx.taskDepth > 0) {
		logger.debug("[mmemory] skipping init: subagent context (taskDepth > 0)", { source: "mmemory" });
		return null;
	}

	const config = loadMmemoryConfig(settings, ctx.cwd);
	if (!config) {
		logger.debug("[mmemory] skipping init: mmemory disabled or config missing", { source: "mmemory" });
		return null;
	}

	const { projectDir, queueDir, indexDir, mentalModelsDir } = resolvePaths(config);

	// Scaffold storage directories on first use
	const isNew = !fs.existsSync(projectDir);
	for (const dir of [queueDir, indexDir, mentalModelsDir]) {
		fs.mkdirSync(dir, { recursive: true });
	}

	// Privacy: write .gitignore files to keep memory data out of git.
	// Written unconditionally (cheap, idempotent) so moving storagePath into a
	// git repo later doesn't silently expose conversation history.
	const GITIGNORE_ALL = "# mmemory — conversation memory is private, never commit\n*\n";
	// At project dir level — excludes queue/, index/, etc.
	const gitignoreProject = path.join(projectDir, ".gitignore");
	if (!fs.existsSync(gitignoreProject)) {
		fs.writeFileSync(gitignoreProject, GITIGNORE_ALL, "utf-8");
	}
	// At storagePath level — excludes all project subdirs if storagePath lands in a repo.
	const gitignoreStorage = path.join(config.storagePath, ".gitignore");
	if (!fs.existsSync(gitignoreStorage)) {
		fs.writeFileSync(
			gitignoreStorage,
			"# mmemory — memory data is private, never commit\n*\n!.gitignore\n",
			"utf-8",
		);
	}

	if (isNew) {
		logger.debug(`[mmemory] Created memory store: ${projectDir}`, { source: "mmemory" });
		console.log(`[mmemory] Created memory store: ${projectDir}`);
		// Auto-generate kb_config.yaml entry so kb_search.py shows this as [external]
		const kbConfigPath = path.join(projectDir, "..", "kb_config.yaml");
		if (!fs.existsSync(kbConfigPath)) {
			fs.writeFileSync(
				kbConfigPath,
				`# Auto-generated by mmemory extension. DO NOT edit the type/handler fields.\n` +
				`${config.projectName}:\n` +
				`  type: external\n` +
				`  handler: mmemory\n` +
				`  description: "Managed by mmemory — use /mmemory commands, not kb_update"\n`,
				"utf-8",
			);
		}
	}

	// Scaffold global/ dir for per-project-tagged cross-project scoping
	if (config.scoping === "per-project-tagged") {
		const globalPaths = resolvePaths({ ...config, projectName: "global" });
		fs.mkdirSync(globalPaths.queueDir, { recursive: true });
		fs.mkdirSync(globalPaths.indexDir, { recursive: true });
	}

	const sessionStartTime = new Date();
	const sessionId = Date.now().toString(36) + Math.random().toString(36).slice(2, 7);

	return {
		config,
		queueDir,
		sessionId,
		sessionStartTime,
		lastRecallSnippet: undefined,
		mentalModelsSnippet: undefined,
		hasRecalledForFirstTurn: false,
		lastRetainedTurn: 0,
		turnCount: 0,
	};
}

// ── Transcript builder ────────────────────────────────────────────────────────
//
// Turn-boundary format: each chunk = one user+assistant pair. The Python server's
// chunk_by_turns() parses **User:** / **Assistant:** markers to reconstruct pairs.
// Memory injection tags are stripped before writing (anti-feedback loop).

interface TranscriptResult {
	transcript: string;
	/** Number of user+assistant pairs included. */
	pairsFound: number;
	/** Number of user messages skipped (empty after tag-stripping). */
	userSkipped: number;
}

function buildTranscript(messages: { role: string; content: unknown }[], contextTurns: number, maxTranscriptChars = 0): TranscriptResult {
	// Walk backwards collecting complete user→assistant pairs, ignoring tool/system entries.
	// contextTurns=0 means take all pairs.
	const pairs: Array<{ user: string; assistant: string }> = [];
	let i = messages.length - 1;
	while (i >= 0 && (contextTurns === 0 || pairs.length < contextTurns)) {
		// Find the next assistant message scanning backwards
		while (i >= 0 && messages[i].role !== "assistant") i--;
		if (i < 0) break;
		const aMsg = messages[i--];
		// Find the user message immediately preceding (skip tool/system entries)
		while (i >= 0 && messages[i].role !== "user") i--;
		if (i < 0) break;
		const uMsg = messages[i--];

		const rawUser = Array.isArray(uMsg.content)
			? (uMsg.content as { type: string; text?: string }[])
				.filter(c => c.type === "text")
				.map(c => c.text ?? "")
				.join(" ")
			: String(uMsg.content ?? "");
		const userText = rawUser.replace(STRIP_TAGS_REGEX, "").trim();
		if (!userText) continue;

		const rawAsst = Array.isArray(aMsg.content)
			? (aMsg.content as { type: string; text?: string }[])
				.filter(c => c.type === "text")
				.map(c => c.text ?? "")
				.join(" ")
			: String(aMsg.content ?? "");
		const assistantText = rawAsst.replace(STRIP_TAGS_REGEX, "").trim();

		pairs.unshift({ user: userText, assistant: assistantText });
	}

	const pairsFound = pairs.length;
	const userSkipped = 0; // legacy field kept for log compat

	const SEP = "\n\n---\n\n";
	const parts = pairs.map(({ user, assistant }) => {
		const turnParts: string[] = [`**User:** ${user}`];
		if (assistant) turnParts.push(`**Assistant:** ${assistant}`);
		return turnParts.join("\n\n");
	});
	let result = parts.join(SEP);

	// Trim from the start (oldest turns first) until the transcript fits.
	if (maxTranscriptChars > 0 && result.length > maxTranscriptChars) {
		let start = 0;
		while (result.length - start > maxTranscriptChars) {
			const nextSep = result.indexOf(SEP, start);
			if (nextSep === -1) break; // single oversized turn — keep it whole
			start = nextSep + SEP.length;
		}
		result = result.slice(start);
	}

	return { transcript: result, pairsFound, userSkipped };
}

async function extractFromTranscript(
	transcript: string,
	config: import("./tools/mmemory/index").MmemoryConfig,
	ctx: ExtensionContext,
): Promise<void> {
	const registry = ctx.modelRegistry;
	const roleValue =
		(config.modelRole && config.modelRole !== "default" ? config.modelRole : undefined) ??
		settings.get("modelRoles.memory" as "modelRoles.smol") ??
		settings.get("modelRoles.smol") ??
		settings.get("modelRoles.default" as "modelRoles.smol");
	const resolved = resolveModelRoleValue(roleValue, registry.getAvailable(), { modelRegistry: registry });
	const model = resolved.model;
	if (!model) return;

	// Use a tool call to force structured output — plain text prompts let the model
	// return code blocks, prose preambles, or empty arrays instead of valid JSON.
	const ExtractionTool = {
		name: "store_facts",
		description: "Store durable facts extracted from the conversation.",
		parameters: Type.Object({
			facts: Type.Array(
				Type.Object({
					fact:     Type.String({ description: "One concise sentence stating a durable fact." }),
					entities: Type.Array(Type.String(), { description: "Key names, paths, or concepts." }),
					date:     Type.String({ description: "YYYY-MM-DD — use today if unknown." }),
				}),
			),
		}),
	};

	const systemPrompt =
		`You are a precise knowledge extractor. ` +
		`Extract durable technical facts from the conversation transcript: decisions made, bugs fixed, ` +
		`config values, constraints, and conventions that will be useful in future sessions. ` +
		`Omit transient details, resolved errors, and anything not useful across sessions. ` +
		`If nothing durable is present, call store_facts with an empty array.`;

	const userPrompt = transcript.length > 8000 ? transcript.slice(0, 8000) : transcript;

	const response = await completeSimple(
		model,
		{
			systemPrompt,
			messages: [{ role: "user", content: [{ type: "text", text: userPrompt }], timestamp: Date.now() }],
			tools: [ExtractionTool],
		},
		{ apiKey, maxTokens: 1024 },
	);

	if (response.stopReason === "error" || !response.content) return;

	// Extract the tool call — fall back to text parsing if the model didn't use the tool.
	const toolCall = response.content.find(
		(c: { type: string }) => c.type === "toolCall",
	) as ToolCall | undefined;

	await executeMemoryExtract(config, async () => {
		if (toolCall?.name === "store_facts") {
			try {
				const validated = validateToolCall([ExtractionTool], toolCall) as { facts: unknown[] };
				return JSON.stringify(validated.facts);
			} catch {
				// fall through to text parse
			}
		}
		// Fallback: model responded with text — try to extract JSON from it
		return (response.content ?? [])
			.filter((c: { type: string; text?: string }) => c.type === "text")
			.map((c: { type: string; text?: string }) => c.text ?? "")
			.join("");
	});
}

async function retainSession(
	state: MmemorySessionState,
	messages: { role: string; content: unknown }[],
	ctx: ExtensionContext | null,
): Promise<void> {
	const userCount = messages.filter(m => m.role === "user").length;
	logger.debug(
		`[mmemory] buildTranscript: total=${messages.length} user=${userCount} contextTurns=${state.config.retainContextTurns} maxChars=${state.config.maxTranscriptChars}`,
		{ source: "mmemory" },
	);
	const { transcript, pairsFound, userSkipped } = buildTranscript(messages, state.config.retainContextTurns, state.config.maxTranscriptChars);
	if (!transcript) {
		logger.debug(
			`[mmemory] retainSession: empty transcript (input had ${userCount} user messages, pairs=${pairsFound} skipped=${userSkipped}), skipping`,
			{ source: "mmemory" },
		);
		return;
	}
	logger.debug(`[mmemory] retainSession: transcript=${transcript.length} chars pairs=${pairsFound} skipped=${userSkipped}`, { source: "mmemory" });

	const today = new Date().toISOString().slice(0, 10);
	// Fixed filename per session — repeated retains overwrite the same file
	const filename = sessionFilename(state.sessionId, state.sessionStartTime);
	const filePath = path.join(state.queueDir, filename);

	fs.writeFileSync(
		filePath,
		`# Memory — ${today}\n\n**Mission:** ${state.config.retainMission}\n\n${transcript}`,
		"utf-8",
	);
	logger.debug(`[mmemory] queue file written: ${filename} (${transcript.length} chars)`, { source: "mmemory" });
	if (state.config.extractionMode === "structured" && ctx) {
		logger.debug("[mmemory] scheduling structured extraction", { source: "mmemory" });
		void extractFromTranscript(transcript, state.config, ctx).catch(e => logger.debug(`[mmemory] extraction failed: ${e}`, { source: "mmemory" }));
	}

	// Server reads queue/*.md, embeds new chunks, deletes processed .md files
	logger.debug("[mmemory] scheduling build", { source: "mmemory" });
	void executeMemoryBuild(state.config).catch(e => logger.warn(`[mmemory] build failed: ${e}`, { source: "mmemory" }));
}

// ── Extension factory ─────────────────────────────────────────────────────────

const sessionMap = new WeakMap<ReadonlySessionManager, MmemorySessionState>();

/**
 * Returns the live MmemoryConfig for the given extension context, or null if the
 * extension is not running for that context (e.g. subagent, mmemory disabled).
 *
 * Tools should prefer this over calling loadMmemoryConfig() directly so they use
 * the extension's already-loaded config rather than re-reading settings on every
 * call. Fall back to loadMmemoryConfig(session.settings, session.cwd) when this
 * returns null (subagent context or extension not initialised).
 *
 * Tool wiring is deferred: ToolSession does not currently expose an ExtensionContext
 * field, so tools cannot call this yet. Once ToolSession gains a `ctx` field of type
 * ExtensionContext, tools/mmemory/*-tool.ts should be updated to call this instead
 * of loadMmemoryConfig directly.
 */
export function getMmemorySessionConfig(
	ctx: import("./extensibility/extensions").ExtensionContext,
): import("./tools/mmemory/index").MmemoryConfig | null {
	return sessionMap.get(ctx.sessionManager)?.config ?? null;
}


// ── Mental models cache invalidation ─────────────────────────────────────────
//
// Keyed by projectDir (string) so the slash command handler can signal a reload
// without needing access to the extension's WeakMap or ExtensionContext.
// Set by invalidateMentalModelsCache(); cleared on next before_agent_start.
const pendingMentalModelReload = new Set<string>();

export function invalidateMentalModelsCache(projectDir: string): void {
	pendingMentalModelReload.add(projectDir);
}

export function createMmemoryExtension(api: ExtensionAPI): void {
	api.setLabel("mmemory");

	api.on("session_start", (_event, ctx) => {
		const state = createSessionState(ctx);
		if (!state) return;
		sessionMap.set(ctx.sessionManager, state);
		logger.debug(`[mmemory] session started: ${state.sessionId} storagePath=${state.config.storagePath} project=${state.config.projectName} extractionMode=${state.config.extractionMode} retainEvery=${state.config.retainEveryNTurns}`, { source: "mmemory" });
	});

	api.on("before_agent_start", async (event, ctx) => {
		const state = sessionMap.get(ctx.sessionManager);
		if (!state) return undefined;

		state.turnCount++;
		const prompt = (event as { prompt?: string }).prompt ?? "";
		const systemPrompt = (event as { systemPrompt?: string }).systemPrompt ?? "";

		// .memory prefix — inject memory_mode directive
		if (prompt.startsWith(".memory ")) {
			const query = prompt.slice(".memory ".length).trim();
			return {
				systemPrompt:
					systemPrompt.trimEnd() +
					"\n\n<memory_mode>\n" +
					"Direct memory request. Use mmemory_recall, mmemory_retain, or mmemory_reflect " +
					"immediately based on the user's intent.\n" +
					`Query: ${query}\n` +
					"</memory_mode>",
			};
		}

		// Lazy-load mental models on first turn; reload when invalidated by /mmemory mm regenerate
		const mmProjectDir = resolvePaths(state.config).projectDir;
		const needsReload = pendingMentalModelReload.has(mmProjectDir);
		if (state.mentalModelsSnippet === undefined || needsReload) {
			if (needsReload) pendingMentalModelReload.delete(mmProjectDir);
			state.mentalModelsSnippet = await loadMentalModels(state.config).catch(() => "");
		}

		// First turn: recall and cache snippet for subsequent turns
		if (!state.hasRecalledForFirstTurn) {
			state.hasRecalledForFirstTurn = true;
			const messages = (event as { messages?: { role: string; content: unknown }[] }).messages ?? [];
			const rawQuery = composeRecallQuery(prompt, messages, state.config.retainContextTurns);
			const query = truncateRecallQuery(rawQuery, prompt, state.config.recallMaxQueryChars);
			logger.debug(`[mmemory] first-turn recall: query=${query.slice(0, 80)}...`, { source: "mmemory" });
			const result = await executeMemoryRecall(
				query, undefined, state.config,
			).catch((e) => {
				logger.debug(`[mmemory] recall failed: ${e}`, { source: "mmemory" });
				// Reset flag so next turn retries — server may not have been ready yet.
				state.hasRecalledForFirstTurn = false;
				return null;
			});
			const snippet = result ? formatRecallForSystemPrompt(result) : undefined;
			if (snippet) {
				state.lastRecallSnippet = snippet;
				logger.debug(`[mmemory] recall injected: ${result?.resultCount} results`, { source: "mmemory" });
			} else {
				logger.debug("[mmemory] recall: no results to inject", { source: "mmemory" });
			}
		}

		// Inject mental models on every turn (after lazy-load ensures they're available)
		const mmBlock = state.mentalModelsSnippet
			? `<mental_models>\n${state.mentalModelsSnippet}\n</mental_models>`
			: undefined;

		if (state.lastRecallSnippet || mmBlock) {
			let extra = systemPrompt.trimEnd();
			if (state.lastRecallSnippet) extra += "\n\n" + state.lastRecallSnippet;
			if (mmBlock) extra += "\n\n" + mmBlock;
			return { systemPrompt: extra };
		}

		return undefined;
	});

	api.on("agent_end", async (event, ctx) => {
		const state = sessionMap.get(ctx.sessionManager);
		if (!state?.config.autoRetain) return;
		const due = state.turnCount - state.lastRetainedTurn >= state.config.retainEveryNTurns;
		logger.debug(`[mmemory] agent_end: turn=${state.turnCount} lastRetained=${state.lastRetainedTurn} every=${state.config.retainEveryNTurns} due=${due}`, { source: "mmemory" });
		if (!due) return;

		// agent_end only carries messages added this turn (new assistant + tool results).
		// We need the full conversation history to build a meaningful transcript.
		const messages = ctx.sessionManager
			.getEntries()
			.filter((e): e is import("./session/session-manager").SessionMessageEntry => e.type === "message")
			.map(e => e.message as { role: string; content: unknown });
		state.lastRetainedTurn = state.turnCount;
		logger.debug(`[mmemory] retain firing: session=${state.sessionId} messages=${messages.length}`, { source: "mmemory" });
		void retainSession(state, messages, ctx).catch((e) => {
			logger.warn(`[mmemory] retain failed: ${e}`, { source: "mmemory" });
		});
	});

	api.on("session.compacting", async (event, ctx) => {
		const state = sessionMap.get(ctx.sessionManager);
		if (!state) return undefined;

		const messages: AgentMessage[] = event.messages ?? [];
		const firstUser = messages.find(m => m.role === "user");
		const rawPrompt = firstUser
			? (Array.isArray(firstUser.content)
					? (firstUser.content as { type: string; text?: string }[])
						.filter(c => c.type === "text")
						.map(c => c.text ?? "")
						.join(" ")
					: String(firstUser.content ?? "")
			  )
			: "project context";
		const rawQuery = composeRecallQuery(
			rawPrompt,
			messages as { role: string; content: unknown }[],
			state.config.retainContextTurns,
		);
		const query = truncateRecallQuery(rawQuery, rawPrompt, state.config.recallMaxQueryChars);

		const result = await executeMemoryRecall(query, undefined, state.config).catch(() => null);
		const snippet = result ? formatRecallForSystemPrompt(result) : undefined;
		return snippet ? { context: [snippet] } : undefined;
	});

	api.on("session_shutdown", async (_event, ctx) => {
		const state = sessionMap.get(ctx.sessionManager);
		if (!state) return;
		// P4-3: retain on shutdown to capture content since the last periodic retain.
		// Only fires if autoRetain is on and there's been at least one turn since last retain.
		if (state.config.autoRetain && state.turnCount > state.lastRetainedTurn) {
			const messages = ctx.sessionManager
				.getEntries()
				.filter((e): e is import("./session/session-manager").SessionMessageEntry => e.type === "message")
				.map(e => e.message as { role: string; content: unknown });
			logger.debug(`[mmemory] shutdown retain: session=${state.sessionId} turns_since_last=${state.turnCount - state.lastRetainedTurn}`, { source: "mmemory" });
			await retainSession(state, messages, ctx).catch(e =>
				logger.warn(`[mmemory] shutdown retain failed: ${e}`, { source: "mmemory" }),
			);
		}
		disposeServerClient(state.config);
		sessionMap.delete(ctx.sessionManager);
	});
}
