/**
 * mmemory — Built-in inline lifecycle extension.
 *
 * Inspired by Hindsight (https://github.com/vectorize-io/hindsight) by Vectorize — Apache 2.0.
 *
 * Registered as an inline ExtensionFactory in sdk.ts alongside createAutoresearchExtension.
 * No sidecar file needed — compiled into the binary.
 *
 * Responsibilities:
 *   - Auto-recall on first agent turn (inject <memories> into system prompt)
 *   - Auto-retain on agent_end (every N turns) — suppressed for subagents (taskDepth > 0)
 *   - .memory / .mem / memory triggers → LLM resolves via mme-*.tool-desc.md (no hardcoded prefix)
 *   - session.compacting → inject recall snippet into compaction context
 *   - Server lifecycle (shared via getOrCreateServerClient in tools/mmemory/index.ts)
 */
import { logger } from "@oh-my-pi/pi-utils";
import * as fs from "node:fs";
import * as path from "node:path";
import { settings } from "./config/settings";
import type { AgentMessage } from "@oh-my-pi/pi-agent-core";
import type { ExtensionAPI, ExtensionContext } from "./extensibility/extensions";
import type { ReadonlySessionManager } from "./session/session-manager";
import { completeSimple, validateToolCall } from "@oh-my-pi/pi-ai";
import type { ToolCall } from "@oh-my-pi/pi-ai";
import { Type } from "@sinclair/typebox";
import { resolveRoleModel } from "./utils/m-utils";
import {
	STRIP_TAGS_REGEX,
	buildConsolidateFn,
	composeRecallQuery,
	disposeServerClient,
	executeMemoryBuild,
	executeMemoryConsolidate,
	executeMemoryRecall,
	formatRecallForSystemPrompt,
	getOrCreateServerClient,
	loadMentalModels,
	loadMmemoryConfig,
	resolvePaths,
	sessionFilename,
	truncateRecallQuery,
} from "./tools/mmemory/index";
import { getRecallScope } from "./tools/mmemory/session-scope";

// ── Session state ─────────────────────────────────────────────────────────────

interface MmemorySessionState {
	readonly config: import("./tools/mmemory/index").MmemoryConfig;
	readonly queueDir: string;
	readonly sessionId: string;
	readonly sessionStartTime: Date;
	lastRecallSnippet: string | undefined;
	mentalModelsSnippet: string | undefined;
	lastRetainedTurn: number;
	turnCount: number;
	consolidationPending: boolean;
	lastConsolidationTs: number;
	lastConsolidationPollAt: number;
	hasRecalledForFirstTurn: boolean;
	/** Chunks fetched by maybePollConsolidation, waiting for agent_end to execute LLM call. */
	pendingConsolidationChunks: unknown[] | null;
}

function createSessionState(ctx: ExtensionContext): MmemorySessionState | null {
	// Subagent guard: subagents must not auto-retain — their exploration transcripts
	// would pollute the memory store with internal monologue.
	if (ctx.taskDepth > 0) {
		logger.debug("[mmemory] skipping init: subagent context (taskDepth > 0)", { source: "mmemory" });
		return null;
	}

	const config = loadMmemoryConfig(settings, ctx.cwd);
	if (!config) {
		logger.debug("[mmemory] skipping init: mmemory disabled or config missing", { source: "mmemory" });
		return null;
	}

	const { projectDir, queueDir, mentalModelsDir } = resolvePaths(config);

	// Scaffold storage directories on first use
	const isNew = !fs.existsSync(projectDir);
	for (const dir of [queueDir, mentalModelsDir]) {
		fs.mkdirSync(dir, { recursive: true });
	}

	// Privacy: write .gitignore files to keep memory data out of git.
	// Written unconditionally (cheap, idempotent) so moving storageRoot into a
	// git repo later doesn't silently expose conversation history.
	const GITIGNORE_ALL = "# mmemory — conversation memory is private, never commit\n*\n";
	// At project dir level — excludes queue/, index/, etc.
	const gitignoreProject = path.join(projectDir, ".gitignore");
	if (!fs.existsSync(gitignoreProject)) {
		fs.writeFileSync(gitignoreProject, GITIGNORE_ALL, "utf-8");
	}
	// At storageRoot level — excludes all contents if storageRoot lands in a repo.
	const gitignoreStorage = path.join(config.storageRoot, ".gitignore");
	if (!fs.existsSync(gitignoreStorage)) {
		fs.writeFileSync(
			gitignoreStorage,
			"# mmemory — memory data is private, never commit\n*\n!.gitignore\n",
			"utf-8",
		);
	}

	if (isNew) {
		logger.debug(`[mmemory] Created memory store: ${projectDir}`, { source: "mmemory" });
		console.log(`[mmemory] Created memory store: ${projectDir}`);
		// Auto-generate kb_config.yaml entry so kb_search.py shows this as [external]
		const kbConfigPath = path.join(projectDir, "..", "kb_config.yaml");
		if (!fs.existsSync(kbConfigPath)) {
			fs.writeFileSync(
				kbConfigPath,
				`# Auto-generated by mmemory extension. DO NOT edit the type/handler fields.\n` +
				`${config.projectLabel}:\n` +
				`  type: external\n` +
				`  handler: mmemory\n` +
				`  description: "Managed by mmemory — use /mmemory commands, not kb_update"\n`,
				"utf-8",
			);
		}
	}

	// per-project-tagged scoping: no extra global dir needed (flat schema, single storageRoot)

	const sessionStartTime = new Date();
	const sessionId = Date.now().toString(36) + Math.random().toString(36).slice(2, 7);

	return {
		config,
		queueDir,
		sessionId,
		sessionStartTime,
		lastRecallSnippet: undefined,
		mentalModelsSnippet: undefined,
		lastRetainedTurn: 0,
		turnCount: 0,
		consolidationPending: false,
		lastConsolidationTs: 0,
		lastConsolidationPollAt: 0,
		pendingConsolidationChunks: null,
		hasRecalledForFirstTurn: false,
	};
}

// ── Transcript builder ────────────────────────────────────────────────────────
//
// Turn-boundary format: each chunk = one user+assistant pair. The Python server's
// chunk_by_turns() parses **User:** / **Assistant:** markers to reconstruct pairs.
// Memory injection tags are stripped before writing (anti-feedback loop).

interface TranscriptResult {
	transcript: string;
	/** Number of user+assistant pairs included. */
	pairsFound: number;
	/** Number of user messages skipped (empty after tag-stripping). */
	userSkipped: number;
}

function buildTranscript(messages: { role: string; content: unknown }[], contextTurns: number, maxTranscriptChars = 0): TranscriptResult {
	// Walk backwards collecting complete user→assistant pairs, ignoring tool/system entries.
	// contextTurns=0 means take all pairs.
	const pairs: Array<{ user: string; assistant: string }> = [];
	let i = messages.length - 1;
	while (i >= 0 && (contextTurns === 0 || pairs.length < contextTurns)) {
		// Find the next assistant message scanning backwards
		while (i >= 0 && messages[i].role !== "assistant") i--;
		if (i < 0) break;
		const aMsg = messages[i--];
		// Find the user message immediately preceding (skip tool/system entries)
		while (i >= 0 && messages[i].role !== "user") i--;
		if (i < 0) break;
		const uMsg = messages[i--];

		const rawUser = Array.isArray(uMsg.content)
			? (uMsg.content as { type: string; text?: string }[])
				.filter(c => c.type === "text")
				.map(c => c.text ?? "")
				.join(" ")
			: String(uMsg.content ?? "");
		const userText = rawUser.replace(STRIP_TAGS_REGEX, "").trim();
		if (!userText) continue;

	// Include assistant text and tool calls; exclude tool results (user-role messages).
	// Follows the same pattern as compaction/utils.ts summariseMessages.
	const textParts: string[] = [];
	const toolCallParts: string[] = [];
	for (const block of (aMsg.content as { type: string; text?: string; name?: string; arguments?: Record<string, unknown> }[])) {
		if (block.type === "text" && block.text) {
			textParts.push(block.text);
		} else if (block.type === "toolCall" && block.name) {
			// Compact format: name(firstPathArg) or name() — enough to know what ran.
			const args = block.arguments ?? {};
			const firstVal = Object.values(args)[0];
			const argStr = typeof firstVal === "string" ? firstVal.slice(0, 80) : "";
			toolCallParts.push(`→ ${block.name}(${argStr})`);
		}
	}
	const rawAsst = [...textParts, ...(toolCallParts.length ? [toolCallParts.join(", ")] : [])].join("\n");
	const assistantText = rawAsst.replace(STRIP_TAGS_REGEX, "").trim();
		pairs.unshift({ user: userText, assistant: assistantText });
	}

	const pairsFound = pairs.length;
	const userSkipped = 0; // legacy field kept for log compat

	const SEP = "\n\n---\n\n";
	const parts = pairs.map(({ user, assistant }) => {
		const turnParts: string[] = [`**User:** ${user}`];
		if (assistant) turnParts.push(`**Assistant:** ${assistant}`);
		return turnParts.join("\n\n");
	});
	let result = parts.join(SEP);

	// Trim from the start (oldest turns first) until the transcript fits.
	if (maxTranscriptChars > 0 && result.length > maxTranscriptChars) {
		let start = 0;
		while (result.length - start > maxTranscriptChars) {
			const nextSep = result.indexOf(SEP, start);
			if (nextSep === -1) break; // single oversized turn — keep it whole
			start = nextSep + SEP.length;
		}
		result = result.slice(start);
	}

	return { transcript: result, pairsFound, userSkipped };
}

async function extractFromTranscript(
	transcript: string,
	config: import("./tools/mmemory/index").MmemoryConfig,
	ctx: ExtensionContext,
): Promise<void> {
	const registry = ctx.modelRegistry;
	const model = resolveRoleModel(config.modelRole, registry, settings, ["memory"]);
	if (!model) return;
}


async function retainSession(
	state: MmemorySessionState,
	messages: { role: string; content: unknown }[],
	ctx: ExtensionContext | null,
	note?: string,
): Promise<void> {
	// DEBUG (cleanup when stable): log every retain attempt
	logger.debug(`[mmemory] retainSession: session=${state.sessionId} messages=${messages.length} note=${note ? "yes" : "no"}`, { source: "mmemory" });

	const userCount = messages.filter(m => m.role === "user").length;
	logger.debug(
		`[mmemory] buildTranscript: total=${messages.length} user=${userCount} contextTurns=${state.config.retainContextTurns} maxChars=${state.config.maxTranscriptChars}`,
		{ source: "mmemory" },
	);
	const { transcript, pairsFound, userSkipped } = buildTranscript(messages, state.config.retainContextTurns, state.config.maxTranscriptChars);
	if (!transcript) {
		logger.debug(
			`[mmemory] retainSession: empty transcript (input had ${userCount} user messages, pairs=${pairsFound} skipped=${userSkipped}), skipping`,
			{ source: "mmemory" },
		);
		return;
	}
	logger.debug(`[mmemory] retainSession: transcript=${transcript.length} chars pairs=${pairsFound} skipped=${userSkipped}`, { source: "mmemory" });

	const today = new Date().toISOString().slice(0, 10);
	// Fixed filename per session — repeated retains overwrite the same file
	const filename = sessionFilename(state.sessionId, state.sessionStartTime);
	const filePath = path.join(state.queueDir, filename);

	const projectLabel = state.config.projectLabel;
	const frontmatter = `---\nproject: ${projectLabel}\nagent_tag: ${state.config.agentTag}\nsource: session\nsession_id: ${state.sessionId}\nts: ${Math.floor(state.sessionStartTime.getTime() / 1000)}\n---\n\n`;
	fs.writeFileSync(
		filePath,
		`${frontmatter}# Memory — ${today}\n\n**Mission:** ${state.config.retainMission}\n\n${transcript}`,
		"utf-8",
	);
	// DEBUG (cleanup when stable): log queue file written
	logger.debug(`[mmemory] retainSession: wrote queue file=${filename} transcriptLen=${transcript.length}`, { source: "mmemory" });
	logger.debug(`[mmemory] queue file written: ${filename} (${transcript.length} chars)`, { source: "mmemory" });


	// Server reads queue/*.md, embeds new chunks, deletes processed .md files
	logger.debug("[mmemory] scheduling build", { source: "mmemory" });
	void executeMemoryBuild(state.config).catch(e => logger.error(`EXCEPTION: [mmemory] build failed: ${e instanceof Error ? e.stack : String(e)}`, { source: "mmemory" }));
}

// ── Extension factory ─────────────────────────────────────────────────────────

const sessionMap = new WeakMap<ReadonlySessionManager, MmemorySessionState>();

/**
 * Returns the live MmemoryConfig for the given extension context, or null if the
 * extension is not running for that context (e.g. subagent, mmemory disabled).
 *
 * Tools should prefer this over calling loadMmemoryConfig() directly so they use
 * the extension's already-loaded config rather than re-reading settings on every
 * call. Fall back to loadMmemoryConfig(session.settings, session.cwd) when this
 * returns null (subagent context or extension not initialised).
 *
 * Tool wiring is deferred: ToolSession does not currently expose an ExtensionContext
 * field, so tools cannot call this yet. Once ToolSession gains a `ctx` field of type
 * ExtensionContext, tools/mmemory/*-tool.ts should be updated to call this instead
 * of loadMmemoryConfig directly.
 */
export function getMmemorySessionConfig(
	ctx: import("./extensibility/extensions").ExtensionContext,
): import("./tools/mmemory/index").MmemoryConfig | null {
	return sessionMap.get(ctx.sessionManager)?.config ?? null;
}

/**
 * Returns the recall snippet that was injected at session start (the snapshot
 * the agent is currently reasoning with). Used by /mmemory view so the panel
 * always shows exactly what was injected — not a fresh re-query that picks up
 * chunks added mid-session.
 *
 * Returns undefined if recall hasn't fired yet (server still starting) or if
 * the session is not tracked (subagent / mmemory disabled).
 */
export function getMmemorySessionSnippet(
	ctx: import("./extensibility/extensions").ExtensionContext,
): string | undefined {
	return sessionMap.get(ctx.sessionManager)?.lastRecallSnippet;
}


/** Returns the live mmemory session state for a session manager, or undefined. */
export function getMmemorySessionState(
	sessionManager: import("./session/session-manager").SessionManager,
): MmemorySessionState | undefined {
	return sessionMap.get(sessionManager);
}


// ── Mental models cache invalidation ─────────────────────────────────────────
//
// Keyed by projectDir (string) so the slash command handler can signal a reload
// without needing access to the extension's WeakMap or ExtensionContext.
// Set by invalidateMentalModelsCache(); cleared on next before_agent_start.
const pendingMentalModelReload = new Set<string>();

export function invalidateMentalModelsCache(projectDir: string): void {
	pendingMentalModelReload.add(projectDir);
}

/**
 * Force an unconditional retain from a slash command or other external caller.
 * Bypasses the retainEveryNTurns gate. Resets lastRetainedTurn so the periodic
 * timer restarts from this point. No-ops if autoRetain is disabled or the session
 * has no messages.
 */
export async function executeManualRetain(
	ctx: import("./extensibility/extensions").ExtensionContext,
	note?: string,
): Promise<{ written: boolean; reason?: string }> {
	const state = sessionMap.get(ctx.sessionManager);
	if (!state) return { written: false, reason: "no mmemory session" };
	if (!state.config.autoRetain) return { written: false, reason: "autoRetain disabled" };
	const messages = ctx.sessionManager
		.getEntries()
		.filter((e): e is import("./session/session-manager").SessionMessageEntry => e.type === "message")
		.map(e => e.message as { role: string; content: unknown });
	if (messages.length === 0) return { written: false, reason: "no messages" };
	state.lastRetainedTurn = state.turnCount;
	logger.debug(`[mmemory] manual retain: session=${state.sessionId} messages=${messages.length}`, { source: "mmemory" });
	await retainSession(state, messages, ctx, note);
	return { written: true };
}

export function createMmemoryExtension(api: ExtensionAPI): void {
	api.setLabel("mmemory");

/**
 * Fire the consolidation poll unconditionally. Checks the server for enough
 * unprocessed session chunks, calls executeMemoryConsolidate if threshold met.
 * Always updates lastConsolidationPollAt so repeated calls within the same
 * interval are cheap no-ops. Safe to call from session_start or agent_end.
 */
/**
 * Phase 1: fetch unprocessed chunks from server and stash on state.
 * Safe to call at session_start — no LLM key needed.
 * No-ops if called within the poll interval.
 */
function maybePollConsolidation(state: MmemorySessionState, _ctx: ExtensionContext): void {
	const now = Date.now();
	// DEBUG (cleanup when stable): log every poll call including skipped ones
	const _elapsed = now - (state.lastConsolidationPollAt ?? 0);
	const _interval = state.config.consolidationPollIntervalMinutes * 60 * 1000;
	logger.debug(`[mmemory] maybePollConsolidation: elapsed=${Math.round(_elapsed/1000)}s interval=${Math.round(_interval/1000)}s willSkip=${_elapsed <= _interval}`, { source: "mmemory" });

	if (now - (state.lastConsolidationPollAt ?? 0) <= state.config.consolidationPollIntervalMinutes * 60 * 1000) return;
	state.lastConsolidationPollAt = now;
	void getOrCreateServerClient(state.config).then(async (client) => {
		const resp = await client.query("get_consolidation_chunks", {
			project_dir: state.config.storageRoot,
			threshold:   state.config.consolidationMinTurns,
			max_turns:   state.config.consolidationMaxTurns,
		}) as any;
		if (resp?.chunks?.length) {
			state.pendingConsolidationChunks = resp.chunks;
			logger.debug(`[mmemory] consolidation: ${resp.chunks.length} chunks queued for next agent_end`, { source: "mmemory" });
		} else {
			logger.debug(`[mmemory] maybePollConsolidation: server returned no chunks count=${resp?.count ?? 0} watermark=${resp?.watermark ?? 0} threshold=${state.config.consolidationMinTurns}`, { source: "mmemory" });
		}
	}).catch(e => logger.error(`EXCEPTION: [mmemory] consolidation poll error: ${e instanceof Error ? e.stack : String(e)}`, { source: "mmemory" }));
}

/**
 * Phase 2: execute the LLM consolidation call with the chunks stashed by maybePollConsolidation.
 * Called at agent_end where modelRegistry has a live API key.
 * Clears pendingConsolidationChunks regardless of outcome.
 */
async function drainPendingConsolidation(state: MmemorySessionState, ctx: ExtensionContext): Promise<void> {
	const chunks = state.pendingConsolidationChunks;
	if (!chunks?.length) {
		logger.debug(`[mmemory] drain: no pending chunks`, { source: "mmemory" });
		return;
	}
	state.pendingConsolidationChunks = null;
	logger.debug(`[mmemory] drain: executing consolidation for ${chunks.length} chunks`, { source: "mmemory" });
	try {
		const fn = buildConsolidateFn(state.config, ctx.modelRegistry, undefined);
		const result = await executeMemoryConsolidate(chunks as any, state.config, fn);
		const msg = `[mmemory] drain: consolidation complete — obs=${result.observationCount} skipped=${result.skipped} msg=${result.message}`;
		if (result.observationCount === 0 && !result.skipped) {
			logger.warn(msg, { source: "mmemory" });
		} else {
			logger.debug(msg, { source: "mmemory" });
		}
	} catch (e) {
		logger.error(`EXCEPTION: [mmemory] drain: consolidation error: ${e instanceof Error ? e.stack : String(e)}`, { source: "mmemory" });
	}
}

	// DEBUG (cleanup when stable): log every session_start — tracks session identity, config, and what fires on load
	api.on("session_start", (_event, ctx) => {
		const state = createSessionState(ctx);
		if (!state) {
			logger.debug("[mmemory] session_start: no state created (mmemory disabled?)", { source: "mmemory" });
			return;
		}
		sessionMap.set(ctx.sessionManager, state);
		logger.debug(`[mmemory] session started: ${state.sessionId} storageRoot=${state.config.storageRoot} extractionMode=${state.config.extractionMode} retainEvery=${state.config.retainEveryNTurns}`, { source: "mmemory" });
	});

	// DEBUG (cleanup when stable): every turn entry — tracks injection, recall, and system prompt modification
	api.on("before_agent_start", async (event, ctx) => {
		const state = sessionMap.get(ctx.sessionManager);
		if (!state) {
			logger.debug("[mmemory] before_agent_start: no state in sessionMap — injection skipped", { source: "mmemory" });
			return undefined;
		}
		state.turnCount++;
		// DEBUG (cleanup when stable): log turn count
		logger.debug(`[mmemory] before_agent_start: turn=${state.turnCount}`, { source: "mmemory" });
		// Mental models: lazy-load once, reload on invalidation
		const mmProjectDir = resolvePaths(state.config).projectDir;
		const needsReload  = pendingMentalModelReload.has(mmProjectDir);
		if (state.mentalModelsSnippet === undefined || needsReload) {
			if (needsReload) pendingMentalModelReload.delete(mmProjectDir);
			state.mentalModelsSnippet = await loadMentalModels(state.config).catch(() => "");
			logger.debug(`[mmemory] before_agent_start: mental models len=${state.mentalModelsSnippet?.length ?? 0}`, { source: "mmemory" });
		}

		// First turn: recall and cache snippet for subsequent turns
		if (!state.hasRecalledForFirstTurn) {
			state.hasRecalledForFirstTurn = true;
			const messages = (event as { messages?: { role: string; content: unknown }[] }).messages ?? [];
			const rawQuery = composeRecallQuery(event.prompt, messages, state.config.retainContextTurns);
			const query = truncateRecallQuery(rawQuery, event.prompt, state.config.recall.maxQueryChars);
			logger.debug(`[mmemory] first-turn recall: query=${query.slice(0, 80)}...`, { source: "mmemory" });
			const result = await executeMemoryRecall(
				query, getRecallScope(ctx.sessionManager), state.config, ctx.modelRegistry, settings,
			).catch((e) => {
				logger.debug(`[mmemory] recall failed: ${e}`, { source: "mmemory" });
				// Reset flag so next turn retries — server may not have been ready yet.
				state.hasRecalledForFirstTurn = false;
				return null;
			});
			const snippet = result ? formatRecallForSystemPrompt(result) : undefined;
			if (snippet) {
				state.lastRecallSnippet = snippet;
				logger.debug(`[mmemory] recall injected: ${result?.resultCount} results`, { source: "mmemory" });
			} else {
				logger.debug("[mmemory] recall: no results to inject", { source: "mmemory" });
			}
		}

		// Inject mental models on every turn (after lazy-load ensures they're available)
		const mmBlock = state.mentalModelsSnippet
			? `<mental_models>\n${state.mentalModelsSnippet}\n</mental_models>`
			: undefined;

		if (state.lastRecallSnippet || mmBlock) {
			let extra = event.systemPrompt.join("\n").trimEnd();
			if (state.lastRecallSnippet) extra += "\n\n" + state.lastRecallSnippet;
			if (mmBlock) extra += "\n\n" + mmBlock;
			return { systemPrompt: [extra] };
		}

		return undefined;
	});

	// DEBUG (cleanup when stable): every turn exit — tracks retain cadence and consolidation drain
	api.on("agent_end", async (_event, ctx) => {
		const state = sessionMap.get(ctx.sessionManager);
		if (!state) {
			logger.debug("[mmemory] agent_end: no state — skipping", { source: "mmemory" });
			return;
		}
		const due = state.turnCount - state.lastRetainedTurn >= state.config.retainEveryNTurns;
		logger.debug(
			`[mmemory] agent_end: turn=${state.turnCount} lastRetained=${state.lastRetainedTurn}` +
			` every=${state.config.retainEveryNTurns} due=${due}` +
			` pendingConsolidChunks=${state.pendingConsolidationChunks?.length ?? "null"}`,
			{ source: "mmemory" },
		);

		if (due && state.config.autoRetain) {
			const messages = ctx.sessionManager
				.getEntries()
				.filter((e): e is import("./session/session-manager").SessionMessageEntry => e.type === "message")
				.map(e => e.message as { role: string; content: unknown });
			state.lastRetainedTurn = state.turnCount;
			logger.debug(`[mmemory] agent_end: retain firing session=${state.sessionId} messages=${messages.length}`, { source: "mmemory" });
			void retainSession(state, messages, ctx).catch((e) => {
				logger.error(`EXCEPTION: [mmemory] agent_end: retain failed: ${e instanceof Error ? e.stack : String(e)}`, { source: "mmemory" });
			});
		}

		void drainPendingConsolidation(state, ctx).then(() => maybePollConsolidation(state, ctx));
	});
	api.on("session.compacting", async (event, ctx) => {
		const state = sessionMap.get(ctx.sessionManager);
		if (!state) return undefined;
		const messages: AgentMessage[] = event.messages ?? [];
		// DEBUG (cleanup when stable): log compaction recall trigger
		logger.debug(`[mmemory] session.compacting: messages=${messages.length}`, { source: "mmemory" });
		const firstUser = messages.find(m => m.role === "user");
		const rawPrompt = firstUser
			? (Array.isArray(firstUser.content)
					? (firstUser.content as { type: string; text?: string }[])
						.filter(c => c.type === "text")
						.map(c => c.text ?? "")
						.join(" ")
					: String(firstUser.content ?? "")
			  )
			: "project context";
		const rawQuery = composeRecallQuery(
			rawPrompt,
			messages as { role: string; content: unknown }[],
			state.config.retainContextTurns,
		);
		const query = truncateRecallQuery(rawQuery, rawPrompt, state.config.recall.maxQueryChars);

		const result = await executeMemoryRecall(query, undefined, state.config).catch(() => null);
		const snippet = result ? formatRecallForSystemPrompt(result) : undefined;
		// DEBUG (cleanup when stable): log compaction recall result
		logger.debug(`[mmemory] session.compacting: recall result=${snippet ? "yes len=" + snippet.length : "no snippet"}`, { source: "mmemory" });
		return snippet ? { context: [snippet] } : undefined;
	});

	api.on("session_shutdown", async (_event, ctx) => {
		const state = sessionMap.get(ctx.sessionManager);
		if (!state) return;
		// DEBUG (cleanup when stable): log every shutdown
		logger.debug(`[mmemory] session_shutdown: session=${state.sessionId} turnCount=${state.turnCount} lastRetained=${state.lastRetainedTurn}`, { source: "mmemory" });
		// P4-3: retain on shutdown to capture content since the last periodic retain.
		// Only fires if autoRetain is on and there's been at least one turn since last retain.
		if (state.config.autoRetain && state.turnCount > state.lastRetainedTurn) {
			const messages = ctx.sessionManager
				.getEntries()
				.filter((e): e is import("./session/session-manager").SessionMessageEntry => e.type === "message")
				.map(e => e.message as { role: string; content: unknown });
			logger.debug(`[mmemory] shutdown retain: session=${state.sessionId} turns_since_last=${state.turnCount - state.lastRetainedTurn}`, { source: "mmemory" });
			await retainSession(state, messages, ctx).catch(e =>
				logger.error(`EXCEPTION: [mmemory] shutdown retain failed: ${e instanceof Error ? e.stack : String(e)}`, { source: "mmemory" }),
			);
		} else {
			logger.debug(`[mmemory] session_shutdown: retain skipped — no new turns or autoRetain disabled`, { source: "mmemory" });
		}
		disposeServerClient(state.config);
		sessionMap.delete(ctx.sessionManager);
	});
}
