
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 */

import addonPath0 from "../native/pi_natives.win32-x64-modern.node" with { type: "file" };
import addonPath1 from "../native/pi_natives.win32-x64-baseline.node" with { type: "file" };

export const embeddedAddon = {
	platformTag: "win32-x64",
	version: "15.0.0",
	files: [
		{ variant: "modern", filename: "pi_natives.win32-x64-modern.node", filePath: addonPath0 },
		{ variant: "baseline", filename: "pi_natives.win32-x64-baseline.node", filePath: addonPath1 },
	],
};
